#server:
#  error:
#    include-stacktrace: never

#server:
#  servlet:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true

logging:
    config: classpath:logback/logback-spring.xml
        
spring:
    profiles:
        active: local #default profile